<?= $this->extend('Layouts/dashboard')?>
<?= $this->section('contenido')?>
                <h1><?= $producto->codprod_id ?></h1>
                <h1><?= $producto->nombre_producto ?></h1>
                <h1><?= $producto->descripcion_producto ?></h1>
                <p><?= $producto->categoria_producto ?></p>
                <p><?= $producto->precio_producto ?></p>
                <p><?= $producto->cantidad_producto ?></p>
                <?= $this->endSection()?>